import { useLayoutEffect, useEffect } from "react";
import useStore, { setEffectivePropsForPage, updateStoreStateFromController } from "../hooks/useStore";
import useIoStore from "../hooks/useIoStore";
import { useNavigate, useLocation } from "react-router-dom";
import { subscribeInternalNavigation } from "../utils/navigate";
import {fetchPageProps} from "../utils/fetchPageProps"
import { Image as Image1 } from "@atrilabs/react-component-manifests/src/manifests/Image/Image.tsx";
import { TextBox as TextBox1 } from "@atrilabs/react-component-manifests/src/manifests/TextBox/TextBox.tsx";
import { Flex as Flex1 } from "@atrilabs/react-component-manifests/src/manifests/Flex/Flex.tsx";
import { Button as Button1 } from "@atrilabs/react-component-manifests/src/manifests/Button/Button.tsx";
import { Input } from "@atrilabs/react-component-manifests/src/manifests/Input/Input.tsx";
import { useImage68Cb, useTextBox47Cb, useImage69Cb, useTextBox48Cb, useImage70Cb, useTextBox49Cb, useImage71Cb, useTextBox50Cb, useImage72Cb, useTextBox51Cb, useImage73Cb, useTextBox52Cb, useImage74Cb, useTextBox53Cb, useImage75Cb, useTextBox54Cb, useImage76Cb, useTextBox55Cb, useTextBox56Cb, useImage77Cb, useImage78Cb, useFlex117Cb, useImage79Cb, useFlex118Cb, useImage80Cb, useFlex119Cb, useImage81Cb, useFlex120Cb, useImage82Cb, useFlex121Cb, useImage83Cb, useFlex122Cb, useImage84Cb, useFlex123Cb, useImage85Cb, useFlex124Cb, useImage86Cb, useFlex125Cb, useFlex126Cb, useImage87Cb, useButton4Cb, useImage88Cb, useTextBox57Cb, useImage89Cb, useTextBox58Cb, useTextBox59Cb, useImage90Cb, useFlex127Cb, useTextBox60Cb, useImage91Cb, useFlex128Cb, useTextBox61Cb, useImage92Cb, useFlex129Cb, useTextBox62Cb, useImage93Cb, useFlex130Cb, useTextBox63Cb, useImage94Cb, useFlex131Cb, useTextBox64Cb, useImage95Cb, useFlex132Cb, useTextBox65Cb, useImage96Cb, useFlex133Cb, useTextBox66Cb, useImage97Cb, useFlex134Cb, useTextBox67Cb, useImage98Cb, useFlex135Cb, useFlex136Cb, useImage99Cb, useTextBox68Cb, useFlex137Cb, useFlex138Cb, useFlex139Cb, useTextBox69Cb, useTextBox70Cb, useFlex140Cb, useFlex141Cb, useFlex142Cb, useFlex143Cb, useFlex144Cb, useFlex145Cb, useFlex146Cb, useFlex147Cb, useFlex148Cb, useFlex149Cb, useFlex150Cb, useFlex151Cb, useFlex152Cb, useFlex153Cb, useFlex154Cb, useFlex155Cb, useFlex156Cb, useFlex157Cb, useFlex158Cb, useFlex159Cb, useFlex160Cb, useFlex161Cb, useFlex162Cb, useFlex163Cb, useFlex164Cb, useFlex165Cb, useFlex166Cb, useFlex167Cb, useFlex168Cb, useFlex169Cb, useFlex170Cb, useFlex171Cb, useImage101Cb, useTextBox72Cb, useTextBox73Cb, useButton6Cb, useImage102Cb, useTextBox74Cb, useFlex181Cb, useFlex182Cb, useFlex183Cb, useFlex184Cb, useFlex185Cb, useFlex186Cb, useTextBox76Cb, useButton8Cb, useImage103Cb, useTextBox77Cb, useImage104Cb, useTextBox78Cb, useFlex187Cb, useFlex188Cb, useFlex189Cb, usetestnameCb, useFlex190Cb, useFlex191Cb, useFlex192Cb, useImage105Cb, useFlex193Cb, useFlex194Cb, useButton9Cb, useTextBox81Cb, useFlex197Cb, useTextBox82Cb, useTextBox83Cb, useFlex200Cb, useFlex201Cb, useTextBox85Cb, useFlex202Cb, useFlex203Cb, useTextBox87Cb, useFlex204Cb, useFlex205Cb, useTextBox89Cb, useButton13Cb, useTextBox91Cb, useFlex208Cb, useFlex209Cb, useTextBox93Cb, useTextBox94Cb, useTextBox95Cb, useTextBox96Cb, useFlex211Cb, usecorrectCb, useexclaimCb, useincorrectCb, usecomment_btnCb, useFlex212Cb, useFlex213Cb, useTextBox97Cb, usecomment_wrapper_1Cb, useFlex215Cb, useFlex216Cb, useImage109Cb, useusername_1Cb, usetime_1Cb, usecomment_1Cb, useFlex218Cb, usecomment_2Cb, usetime_2Cb, useusername_2Cb, useImage110Cb, useFlex219Cb, useFlex220Cb, usecomment_wrapper_2Cb, useImage111Cb, useusername_3Cb, usetime_3Cb, usecomment_3Cb, useFlex222Cb, useFlex223Cb, usecomment_wrapper_3Cb, usecomment_input_wrapperCb, usecomment_inputCb, useButton20Cb, useButton49Cb, useButton50Cb, useButton51Cb, useButton52Cb, useButton58Cb, useTextBox198Cb, useTextBox199Cb, useButton59Cb, useTextBox200Cb, useButton60Cb, useTextBox201Cb, useButton61Cb, useTextBox202Cb, useButton62Cb, useImage148Cb, useFlex372Cb, useTextBox203Cb, useFlex373Cb, useTextBox204Cb, useFlex374Cb, useTextBox205Cb, useFlex375Cb, useTextBox206Cb, useFlex376Cb, useTextBox207Cb, useFlex377Cb, useFlex378Cb, useFlex379Cb, useFlex380Cb, useFlex381Cb, useFlex382Cb, useFlex386Cb, useButton63Cb, useTextBox208Cb, useTextBox209Cb, useButton64Cb, useTextBox210Cb, useButton65Cb, useTextBox211Cb, useButton66Cb, useTextBox212Cb, useButton67Cb, useoutput_imgCb, useFlex387Cb, usedriver_nameCb, useFlex388Cb, uselicenseCb, useFlex389Cb, usedobCb, useFlex390Cb, useexpiryCb, useFlex391Cb, useaddressCb, useoutput_img_wrapperCb, useFlex393Cb, useFlex394Cb, useFlex395Cb, useFlex396Cb, useFlex397Cb, useFlex398Cb, useFlex399Cb, useFlex400Cb, useFlex401Cb, usesubmitCb, usecomment_btn_wrapperCb, useImage151Cb } from "../page-cbs/viewtest";

export default function Viewtest() {
  const navigate = useNavigate();
  useEffect(() => {
    const unsub = subscribeInternalNavigation((url) => {
      navigate(url);
    });
    return unsub;
  }, [navigate]);

  const location = useLocation();
  useLayoutEffect(()=>{
    fetchPageProps(location.pathname, location.search).then((res)=>{
      updateStoreStateFromController(res.pageName, res.pageState)
    })
  }, [])

  useLayoutEffect(()=>{
    setEffectivePropsForPage("viewtest")
  }, [])

  useEffect(()=>{
    const onResize = ()=>{
      setEffectivePropsForPage("viewtest")
    };
    window.addEventListener("resize", onResize);
    return ()=>{
      window.removeEventListener("resize", onResize);
    }
  }, [])

  const Image68Props = useStore((state)=>state["viewtest"]["Image68"]);
const Image68IoProps = useIoStore((state)=>state["viewtest"]["Image68"]);
const Image68Cb = useImage68Cb()
const TextBox47Props = useStore((state)=>state["viewtest"]["TextBox47"]);
const TextBox47IoProps = useIoStore((state)=>state["viewtest"]["TextBox47"]);
const TextBox47Cb = useTextBox47Cb()
const Image69Props = useStore((state)=>state["viewtest"]["Image69"]);
const Image69IoProps = useIoStore((state)=>state["viewtest"]["Image69"]);
const Image69Cb = useImage69Cb()
const TextBox48Props = useStore((state)=>state["viewtest"]["TextBox48"]);
const TextBox48IoProps = useIoStore((state)=>state["viewtest"]["TextBox48"]);
const TextBox48Cb = useTextBox48Cb()
const Image70Props = useStore((state)=>state["viewtest"]["Image70"]);
const Image70IoProps = useIoStore((state)=>state["viewtest"]["Image70"]);
const Image70Cb = useImage70Cb()
const TextBox49Props = useStore((state)=>state["viewtest"]["TextBox49"]);
const TextBox49IoProps = useIoStore((state)=>state["viewtest"]["TextBox49"]);
const TextBox49Cb = useTextBox49Cb()
const Image71Props = useStore((state)=>state["viewtest"]["Image71"]);
const Image71IoProps = useIoStore((state)=>state["viewtest"]["Image71"]);
const Image71Cb = useImage71Cb()
const TextBox50Props = useStore((state)=>state["viewtest"]["TextBox50"]);
const TextBox50IoProps = useIoStore((state)=>state["viewtest"]["TextBox50"]);
const TextBox50Cb = useTextBox50Cb()
const Image72Props = useStore((state)=>state["viewtest"]["Image72"]);
const Image72IoProps = useIoStore((state)=>state["viewtest"]["Image72"]);
const Image72Cb = useImage72Cb()
const TextBox51Props = useStore((state)=>state["viewtest"]["TextBox51"]);
const TextBox51IoProps = useIoStore((state)=>state["viewtest"]["TextBox51"]);
const TextBox51Cb = useTextBox51Cb()
const Image73Props = useStore((state)=>state["viewtest"]["Image73"]);
const Image73IoProps = useIoStore((state)=>state["viewtest"]["Image73"]);
const Image73Cb = useImage73Cb()
const TextBox52Props = useStore((state)=>state["viewtest"]["TextBox52"]);
const TextBox52IoProps = useIoStore((state)=>state["viewtest"]["TextBox52"]);
const TextBox52Cb = useTextBox52Cb()
const Image74Props = useStore((state)=>state["viewtest"]["Image74"]);
const Image74IoProps = useIoStore((state)=>state["viewtest"]["Image74"]);
const Image74Cb = useImage74Cb()
const TextBox53Props = useStore((state)=>state["viewtest"]["TextBox53"]);
const TextBox53IoProps = useIoStore((state)=>state["viewtest"]["TextBox53"]);
const TextBox53Cb = useTextBox53Cb()
const Image75Props = useStore((state)=>state["viewtest"]["Image75"]);
const Image75IoProps = useIoStore((state)=>state["viewtest"]["Image75"]);
const Image75Cb = useImage75Cb()
const TextBox54Props = useStore((state)=>state["viewtest"]["TextBox54"]);
const TextBox54IoProps = useIoStore((state)=>state["viewtest"]["TextBox54"]);
const TextBox54Cb = useTextBox54Cb()
const Image76Props = useStore((state)=>state["viewtest"]["Image76"]);
const Image76IoProps = useIoStore((state)=>state["viewtest"]["Image76"]);
const Image76Cb = useImage76Cb()
const TextBox55Props = useStore((state)=>state["viewtest"]["TextBox55"]);
const TextBox55IoProps = useIoStore((state)=>state["viewtest"]["TextBox55"]);
const TextBox55Cb = useTextBox55Cb()
const TextBox56Props = useStore((state)=>state["viewtest"]["TextBox56"]);
const TextBox56IoProps = useIoStore((state)=>state["viewtest"]["TextBox56"]);
const TextBox56Cb = useTextBox56Cb()
const Image77Props = useStore((state)=>state["viewtest"]["Image77"]);
const Image77IoProps = useIoStore((state)=>state["viewtest"]["Image77"]);
const Image77Cb = useImage77Cb()
const Image78Props = useStore((state)=>state["viewtest"]["Image78"]);
const Image78IoProps = useIoStore((state)=>state["viewtest"]["Image78"]);
const Image78Cb = useImage78Cb()
const Flex117Props = useStore((state)=>state["viewtest"]["Flex117"]);
const Flex117IoProps = useIoStore((state)=>state["viewtest"]["Flex117"]);
const Flex117Cb = useFlex117Cb()
const Image79Props = useStore((state)=>state["viewtest"]["Image79"]);
const Image79IoProps = useIoStore((state)=>state["viewtest"]["Image79"]);
const Image79Cb = useImage79Cb()
const Flex118Props = useStore((state)=>state["viewtest"]["Flex118"]);
const Flex118IoProps = useIoStore((state)=>state["viewtest"]["Flex118"]);
const Flex118Cb = useFlex118Cb()
const Image80Props = useStore((state)=>state["viewtest"]["Image80"]);
const Image80IoProps = useIoStore((state)=>state["viewtest"]["Image80"]);
const Image80Cb = useImage80Cb()
const Flex119Props = useStore((state)=>state["viewtest"]["Flex119"]);
const Flex119IoProps = useIoStore((state)=>state["viewtest"]["Flex119"]);
const Flex119Cb = useFlex119Cb()
const Image81Props = useStore((state)=>state["viewtest"]["Image81"]);
const Image81IoProps = useIoStore((state)=>state["viewtest"]["Image81"]);
const Image81Cb = useImage81Cb()
const Flex120Props = useStore((state)=>state["viewtest"]["Flex120"]);
const Flex120IoProps = useIoStore((state)=>state["viewtest"]["Flex120"]);
const Flex120Cb = useFlex120Cb()
const Image82Props = useStore((state)=>state["viewtest"]["Image82"]);
const Image82IoProps = useIoStore((state)=>state["viewtest"]["Image82"]);
const Image82Cb = useImage82Cb()
const Flex121Props = useStore((state)=>state["viewtest"]["Flex121"]);
const Flex121IoProps = useIoStore((state)=>state["viewtest"]["Flex121"]);
const Flex121Cb = useFlex121Cb()
const Image83Props = useStore((state)=>state["viewtest"]["Image83"]);
const Image83IoProps = useIoStore((state)=>state["viewtest"]["Image83"]);
const Image83Cb = useImage83Cb()
const Flex122Props = useStore((state)=>state["viewtest"]["Flex122"]);
const Flex122IoProps = useIoStore((state)=>state["viewtest"]["Flex122"]);
const Flex122Cb = useFlex122Cb()
const Image84Props = useStore((state)=>state["viewtest"]["Image84"]);
const Image84IoProps = useIoStore((state)=>state["viewtest"]["Image84"]);
const Image84Cb = useImage84Cb()
const Flex123Props = useStore((state)=>state["viewtest"]["Flex123"]);
const Flex123IoProps = useIoStore((state)=>state["viewtest"]["Flex123"]);
const Flex123Cb = useFlex123Cb()
const Image85Props = useStore((state)=>state["viewtest"]["Image85"]);
const Image85IoProps = useIoStore((state)=>state["viewtest"]["Image85"]);
const Image85Cb = useImage85Cb()
const Flex124Props = useStore((state)=>state["viewtest"]["Flex124"]);
const Flex124IoProps = useIoStore((state)=>state["viewtest"]["Flex124"]);
const Flex124Cb = useFlex124Cb()
const Image86Props = useStore((state)=>state["viewtest"]["Image86"]);
const Image86IoProps = useIoStore((state)=>state["viewtest"]["Image86"]);
const Image86Cb = useImage86Cb()
const Flex125Props = useStore((state)=>state["viewtest"]["Flex125"]);
const Flex125IoProps = useIoStore((state)=>state["viewtest"]["Flex125"]);
const Flex125Cb = useFlex125Cb()
const Flex126Props = useStore((state)=>state["viewtest"]["Flex126"]);
const Flex126IoProps = useIoStore((state)=>state["viewtest"]["Flex126"]);
const Flex126Cb = useFlex126Cb()
const Image87Props = useStore((state)=>state["viewtest"]["Image87"]);
const Image87IoProps = useIoStore((state)=>state["viewtest"]["Image87"]);
const Image87Cb = useImage87Cb()
const Button4Props = useStore((state)=>state["viewtest"]["Button4"]);
const Button4IoProps = useIoStore((state)=>state["viewtest"]["Button4"]);
const Button4Cb = useButton4Cb()
const Image88Props = useStore((state)=>state["viewtest"]["Image88"]);
const Image88IoProps = useIoStore((state)=>state["viewtest"]["Image88"]);
const Image88Cb = useImage88Cb()
const TextBox57Props = useStore((state)=>state["viewtest"]["TextBox57"]);
const TextBox57IoProps = useIoStore((state)=>state["viewtest"]["TextBox57"]);
const TextBox57Cb = useTextBox57Cb()
const Image89Props = useStore((state)=>state["viewtest"]["Image89"]);
const Image89IoProps = useIoStore((state)=>state["viewtest"]["Image89"]);
const Image89Cb = useImage89Cb()
const TextBox58Props = useStore((state)=>state["viewtest"]["TextBox58"]);
const TextBox58IoProps = useIoStore((state)=>state["viewtest"]["TextBox58"]);
const TextBox58Cb = useTextBox58Cb()
const TextBox59Props = useStore((state)=>state["viewtest"]["TextBox59"]);
const TextBox59IoProps = useIoStore((state)=>state["viewtest"]["TextBox59"]);
const TextBox59Cb = useTextBox59Cb()
const Image90Props = useStore((state)=>state["viewtest"]["Image90"]);
const Image90IoProps = useIoStore((state)=>state["viewtest"]["Image90"]);
const Image90Cb = useImage90Cb()
const Flex127Props = useStore((state)=>state["viewtest"]["Flex127"]);
const Flex127IoProps = useIoStore((state)=>state["viewtest"]["Flex127"]);
const Flex127Cb = useFlex127Cb()
const TextBox60Props = useStore((state)=>state["viewtest"]["TextBox60"]);
const TextBox60IoProps = useIoStore((state)=>state["viewtest"]["TextBox60"]);
const TextBox60Cb = useTextBox60Cb()
const Image91Props = useStore((state)=>state["viewtest"]["Image91"]);
const Image91IoProps = useIoStore((state)=>state["viewtest"]["Image91"]);
const Image91Cb = useImage91Cb()
const Flex128Props = useStore((state)=>state["viewtest"]["Flex128"]);
const Flex128IoProps = useIoStore((state)=>state["viewtest"]["Flex128"]);
const Flex128Cb = useFlex128Cb()
const TextBox61Props = useStore((state)=>state["viewtest"]["TextBox61"]);
const TextBox61IoProps = useIoStore((state)=>state["viewtest"]["TextBox61"]);
const TextBox61Cb = useTextBox61Cb()
const Image92Props = useStore((state)=>state["viewtest"]["Image92"]);
const Image92IoProps = useIoStore((state)=>state["viewtest"]["Image92"]);
const Image92Cb = useImage92Cb()
const Flex129Props = useStore((state)=>state["viewtest"]["Flex129"]);
const Flex129IoProps = useIoStore((state)=>state["viewtest"]["Flex129"]);
const Flex129Cb = useFlex129Cb()
const TextBox62Props = useStore((state)=>state["viewtest"]["TextBox62"]);
const TextBox62IoProps = useIoStore((state)=>state["viewtest"]["TextBox62"]);
const TextBox62Cb = useTextBox62Cb()
const Image93Props = useStore((state)=>state["viewtest"]["Image93"]);
const Image93IoProps = useIoStore((state)=>state["viewtest"]["Image93"]);
const Image93Cb = useImage93Cb()
const Flex130Props = useStore((state)=>state["viewtest"]["Flex130"]);
const Flex130IoProps = useIoStore((state)=>state["viewtest"]["Flex130"]);
const Flex130Cb = useFlex130Cb()
const TextBox63Props = useStore((state)=>state["viewtest"]["TextBox63"]);
const TextBox63IoProps = useIoStore((state)=>state["viewtest"]["TextBox63"]);
const TextBox63Cb = useTextBox63Cb()
const Image94Props = useStore((state)=>state["viewtest"]["Image94"]);
const Image94IoProps = useIoStore((state)=>state["viewtest"]["Image94"]);
const Image94Cb = useImage94Cb()
const Flex131Props = useStore((state)=>state["viewtest"]["Flex131"]);
const Flex131IoProps = useIoStore((state)=>state["viewtest"]["Flex131"]);
const Flex131Cb = useFlex131Cb()
const TextBox64Props = useStore((state)=>state["viewtest"]["TextBox64"]);
const TextBox64IoProps = useIoStore((state)=>state["viewtest"]["TextBox64"]);
const TextBox64Cb = useTextBox64Cb()
const Image95Props = useStore((state)=>state["viewtest"]["Image95"]);
const Image95IoProps = useIoStore((state)=>state["viewtest"]["Image95"]);
const Image95Cb = useImage95Cb()
const Flex132Props = useStore((state)=>state["viewtest"]["Flex132"]);
const Flex132IoProps = useIoStore((state)=>state["viewtest"]["Flex132"]);
const Flex132Cb = useFlex132Cb()
const TextBox65Props = useStore((state)=>state["viewtest"]["TextBox65"]);
const TextBox65IoProps = useIoStore((state)=>state["viewtest"]["TextBox65"]);
const TextBox65Cb = useTextBox65Cb()
const Image96Props = useStore((state)=>state["viewtest"]["Image96"]);
const Image96IoProps = useIoStore((state)=>state["viewtest"]["Image96"]);
const Image96Cb = useImage96Cb()
const Flex133Props = useStore((state)=>state["viewtest"]["Flex133"]);
const Flex133IoProps = useIoStore((state)=>state["viewtest"]["Flex133"]);
const Flex133Cb = useFlex133Cb()
const TextBox66Props = useStore((state)=>state["viewtest"]["TextBox66"]);
const TextBox66IoProps = useIoStore((state)=>state["viewtest"]["TextBox66"]);
const TextBox66Cb = useTextBox66Cb()
const Image97Props = useStore((state)=>state["viewtest"]["Image97"]);
const Image97IoProps = useIoStore((state)=>state["viewtest"]["Image97"]);
const Image97Cb = useImage97Cb()
const Flex134Props = useStore((state)=>state["viewtest"]["Flex134"]);
const Flex134IoProps = useIoStore((state)=>state["viewtest"]["Flex134"]);
const Flex134Cb = useFlex134Cb()
const TextBox67Props = useStore((state)=>state["viewtest"]["TextBox67"]);
const TextBox67IoProps = useIoStore((state)=>state["viewtest"]["TextBox67"]);
const TextBox67Cb = useTextBox67Cb()
const Image98Props = useStore((state)=>state["viewtest"]["Image98"]);
const Image98IoProps = useIoStore((state)=>state["viewtest"]["Image98"]);
const Image98Cb = useImage98Cb()
const Flex135Props = useStore((state)=>state["viewtest"]["Flex135"]);
const Flex135IoProps = useIoStore((state)=>state["viewtest"]["Flex135"]);
const Flex135Cb = useFlex135Cb()
const Flex136Props = useStore((state)=>state["viewtest"]["Flex136"]);
const Flex136IoProps = useIoStore((state)=>state["viewtest"]["Flex136"]);
const Flex136Cb = useFlex136Cb()
const Image99Props = useStore((state)=>state["viewtest"]["Image99"]);
const Image99IoProps = useIoStore((state)=>state["viewtest"]["Image99"]);
const Image99Cb = useImage99Cb()
const TextBox68Props = useStore((state)=>state["viewtest"]["TextBox68"]);
const TextBox68IoProps = useIoStore((state)=>state["viewtest"]["TextBox68"]);
const TextBox68Cb = useTextBox68Cb()
const Flex137Props = useStore((state)=>state["viewtest"]["Flex137"]);
const Flex137IoProps = useIoStore((state)=>state["viewtest"]["Flex137"]);
const Flex137Cb = useFlex137Cb()
const Flex138Props = useStore((state)=>state["viewtest"]["Flex138"]);
const Flex138IoProps = useIoStore((state)=>state["viewtest"]["Flex138"]);
const Flex138Cb = useFlex138Cb()
const Flex139Props = useStore((state)=>state["viewtest"]["Flex139"]);
const Flex139IoProps = useIoStore((state)=>state["viewtest"]["Flex139"]);
const Flex139Cb = useFlex139Cb()
const TextBox69Props = useStore((state)=>state["viewtest"]["TextBox69"]);
const TextBox69IoProps = useIoStore((state)=>state["viewtest"]["TextBox69"]);
const TextBox69Cb = useTextBox69Cb()
const TextBox70Props = useStore((state)=>state["viewtest"]["TextBox70"]);
const TextBox70IoProps = useIoStore((state)=>state["viewtest"]["TextBox70"]);
const TextBox70Cb = useTextBox70Cb()
const Flex140Props = useStore((state)=>state["viewtest"]["Flex140"]);
const Flex140IoProps = useIoStore((state)=>state["viewtest"]["Flex140"]);
const Flex140Cb = useFlex140Cb()
const Flex141Props = useStore((state)=>state["viewtest"]["Flex141"]);
const Flex141IoProps = useIoStore((state)=>state["viewtest"]["Flex141"]);
const Flex141Cb = useFlex141Cb()
const Flex142Props = useStore((state)=>state["viewtest"]["Flex142"]);
const Flex142IoProps = useIoStore((state)=>state["viewtest"]["Flex142"]);
const Flex142Cb = useFlex142Cb()
const Flex143Props = useStore((state)=>state["viewtest"]["Flex143"]);
const Flex143IoProps = useIoStore((state)=>state["viewtest"]["Flex143"]);
const Flex143Cb = useFlex143Cb()
const Flex144Props = useStore((state)=>state["viewtest"]["Flex144"]);
const Flex144IoProps = useIoStore((state)=>state["viewtest"]["Flex144"]);
const Flex144Cb = useFlex144Cb()
const Flex145Props = useStore((state)=>state["viewtest"]["Flex145"]);
const Flex145IoProps = useIoStore((state)=>state["viewtest"]["Flex145"]);
const Flex145Cb = useFlex145Cb()
const Flex146Props = useStore((state)=>state["viewtest"]["Flex146"]);
const Flex146IoProps = useIoStore((state)=>state["viewtest"]["Flex146"]);
const Flex146Cb = useFlex146Cb()
const Flex147Props = useStore((state)=>state["viewtest"]["Flex147"]);
const Flex147IoProps = useIoStore((state)=>state["viewtest"]["Flex147"]);
const Flex147Cb = useFlex147Cb()
const Flex148Props = useStore((state)=>state["viewtest"]["Flex148"]);
const Flex148IoProps = useIoStore((state)=>state["viewtest"]["Flex148"]);
const Flex148Cb = useFlex148Cb()
const Flex149Props = useStore((state)=>state["viewtest"]["Flex149"]);
const Flex149IoProps = useIoStore((state)=>state["viewtest"]["Flex149"]);
const Flex149Cb = useFlex149Cb()
const Flex150Props = useStore((state)=>state["viewtest"]["Flex150"]);
const Flex150IoProps = useIoStore((state)=>state["viewtest"]["Flex150"]);
const Flex150Cb = useFlex150Cb()
const Flex151Props = useStore((state)=>state["viewtest"]["Flex151"]);
const Flex151IoProps = useIoStore((state)=>state["viewtest"]["Flex151"]);
const Flex151Cb = useFlex151Cb()
const Flex152Props = useStore((state)=>state["viewtest"]["Flex152"]);
const Flex152IoProps = useIoStore((state)=>state["viewtest"]["Flex152"]);
const Flex152Cb = useFlex152Cb()
const Flex153Props = useStore((state)=>state["viewtest"]["Flex153"]);
const Flex153IoProps = useIoStore((state)=>state["viewtest"]["Flex153"]);
const Flex153Cb = useFlex153Cb()
const Flex154Props = useStore((state)=>state["viewtest"]["Flex154"]);
const Flex154IoProps = useIoStore((state)=>state["viewtest"]["Flex154"]);
const Flex154Cb = useFlex154Cb()
const Flex155Props = useStore((state)=>state["viewtest"]["Flex155"]);
const Flex155IoProps = useIoStore((state)=>state["viewtest"]["Flex155"]);
const Flex155Cb = useFlex155Cb()
const Flex156Props = useStore((state)=>state["viewtest"]["Flex156"]);
const Flex156IoProps = useIoStore((state)=>state["viewtest"]["Flex156"]);
const Flex156Cb = useFlex156Cb()
const Flex157Props = useStore((state)=>state["viewtest"]["Flex157"]);
const Flex157IoProps = useIoStore((state)=>state["viewtest"]["Flex157"]);
const Flex157Cb = useFlex157Cb()
const Flex158Props = useStore((state)=>state["viewtest"]["Flex158"]);
const Flex158IoProps = useIoStore((state)=>state["viewtest"]["Flex158"]);
const Flex158Cb = useFlex158Cb()
const Flex159Props = useStore((state)=>state["viewtest"]["Flex159"]);
const Flex159IoProps = useIoStore((state)=>state["viewtest"]["Flex159"]);
const Flex159Cb = useFlex159Cb()
const Flex160Props = useStore((state)=>state["viewtest"]["Flex160"]);
const Flex160IoProps = useIoStore((state)=>state["viewtest"]["Flex160"]);
const Flex160Cb = useFlex160Cb()
const Flex161Props = useStore((state)=>state["viewtest"]["Flex161"]);
const Flex161IoProps = useIoStore((state)=>state["viewtest"]["Flex161"]);
const Flex161Cb = useFlex161Cb()
const Flex162Props = useStore((state)=>state["viewtest"]["Flex162"]);
const Flex162IoProps = useIoStore((state)=>state["viewtest"]["Flex162"]);
const Flex162Cb = useFlex162Cb()
const Flex163Props = useStore((state)=>state["viewtest"]["Flex163"]);
const Flex163IoProps = useIoStore((state)=>state["viewtest"]["Flex163"]);
const Flex163Cb = useFlex163Cb()
const Flex164Props = useStore((state)=>state["viewtest"]["Flex164"]);
const Flex164IoProps = useIoStore((state)=>state["viewtest"]["Flex164"]);
const Flex164Cb = useFlex164Cb()
const Flex165Props = useStore((state)=>state["viewtest"]["Flex165"]);
const Flex165IoProps = useIoStore((state)=>state["viewtest"]["Flex165"]);
const Flex165Cb = useFlex165Cb()
const Flex166Props = useStore((state)=>state["viewtest"]["Flex166"]);
const Flex166IoProps = useIoStore((state)=>state["viewtest"]["Flex166"]);
const Flex166Cb = useFlex166Cb()
const Flex167Props = useStore((state)=>state["viewtest"]["Flex167"]);
const Flex167IoProps = useIoStore((state)=>state["viewtest"]["Flex167"]);
const Flex167Cb = useFlex167Cb()
const Flex168Props = useStore((state)=>state["viewtest"]["Flex168"]);
const Flex168IoProps = useIoStore((state)=>state["viewtest"]["Flex168"]);
const Flex168Cb = useFlex168Cb()
const Flex169Props = useStore((state)=>state["viewtest"]["Flex169"]);
const Flex169IoProps = useIoStore((state)=>state["viewtest"]["Flex169"]);
const Flex169Cb = useFlex169Cb()
const Flex170Props = useStore((state)=>state["viewtest"]["Flex170"]);
const Flex170IoProps = useIoStore((state)=>state["viewtest"]["Flex170"]);
const Flex170Cb = useFlex170Cb()
const Flex171Props = useStore((state)=>state["viewtest"]["Flex171"]);
const Flex171IoProps = useIoStore((state)=>state["viewtest"]["Flex171"]);
const Flex171Cb = useFlex171Cb()
const Image101Props = useStore((state)=>state["viewtest"]["Image101"]);
const Image101IoProps = useIoStore((state)=>state["viewtest"]["Image101"]);
const Image101Cb = useImage101Cb()
const TextBox72Props = useStore((state)=>state["viewtest"]["TextBox72"]);
const TextBox72IoProps = useIoStore((state)=>state["viewtest"]["TextBox72"]);
const TextBox72Cb = useTextBox72Cb()
const TextBox73Props = useStore((state)=>state["viewtest"]["TextBox73"]);
const TextBox73IoProps = useIoStore((state)=>state["viewtest"]["TextBox73"]);
const TextBox73Cb = useTextBox73Cb()
const Button6Props = useStore((state)=>state["viewtest"]["Button6"]);
const Button6IoProps = useIoStore((state)=>state["viewtest"]["Button6"]);
const Button6Cb = useButton6Cb()
const Image102Props = useStore((state)=>state["viewtest"]["Image102"]);
const Image102IoProps = useIoStore((state)=>state["viewtest"]["Image102"]);
const Image102Cb = useImage102Cb()
const TextBox74Props = useStore((state)=>state["viewtest"]["TextBox74"]);
const TextBox74IoProps = useIoStore((state)=>state["viewtest"]["TextBox74"]);
const TextBox74Cb = useTextBox74Cb()
const Flex181Props = useStore((state)=>state["viewtest"]["Flex181"]);
const Flex181IoProps = useIoStore((state)=>state["viewtest"]["Flex181"]);
const Flex181Cb = useFlex181Cb()
const Flex182Props = useStore((state)=>state["viewtest"]["Flex182"]);
const Flex182IoProps = useIoStore((state)=>state["viewtest"]["Flex182"]);
const Flex182Cb = useFlex182Cb()
const Flex183Props = useStore((state)=>state["viewtest"]["Flex183"]);
const Flex183IoProps = useIoStore((state)=>state["viewtest"]["Flex183"]);
const Flex183Cb = useFlex183Cb()
const Flex184Props = useStore((state)=>state["viewtest"]["Flex184"]);
const Flex184IoProps = useIoStore((state)=>state["viewtest"]["Flex184"]);
const Flex184Cb = useFlex184Cb()
const Flex185Props = useStore((state)=>state["viewtest"]["Flex185"]);
const Flex185IoProps = useIoStore((state)=>state["viewtest"]["Flex185"]);
const Flex185Cb = useFlex185Cb()
const Flex186Props = useStore((state)=>state["viewtest"]["Flex186"]);
const Flex186IoProps = useIoStore((state)=>state["viewtest"]["Flex186"]);
const Flex186Cb = useFlex186Cb()
const TextBox76Props = useStore((state)=>state["viewtest"]["TextBox76"]);
const TextBox76IoProps = useIoStore((state)=>state["viewtest"]["TextBox76"]);
const TextBox76Cb = useTextBox76Cb()
const Button8Props = useStore((state)=>state["viewtest"]["Button8"]);
const Button8IoProps = useIoStore((state)=>state["viewtest"]["Button8"]);
const Button8Cb = useButton8Cb()
const Image103Props = useStore((state)=>state["viewtest"]["Image103"]);
const Image103IoProps = useIoStore((state)=>state["viewtest"]["Image103"]);
const Image103Cb = useImage103Cb()
const TextBox77Props = useStore((state)=>state["viewtest"]["TextBox77"]);
const TextBox77IoProps = useIoStore((state)=>state["viewtest"]["TextBox77"]);
const TextBox77Cb = useTextBox77Cb()
const Image104Props = useStore((state)=>state["viewtest"]["Image104"]);
const Image104IoProps = useIoStore((state)=>state["viewtest"]["Image104"]);
const Image104Cb = useImage104Cb()
const TextBox78Props = useStore((state)=>state["viewtest"]["TextBox78"]);
const TextBox78IoProps = useIoStore((state)=>state["viewtest"]["TextBox78"]);
const TextBox78Cb = useTextBox78Cb()
const Flex187Props = useStore((state)=>state["viewtest"]["Flex187"]);
const Flex187IoProps = useIoStore((state)=>state["viewtest"]["Flex187"]);
const Flex187Cb = useFlex187Cb()
const Flex188Props = useStore((state)=>state["viewtest"]["Flex188"]);
const Flex188IoProps = useIoStore((state)=>state["viewtest"]["Flex188"]);
const Flex188Cb = useFlex188Cb()
const Flex189Props = useStore((state)=>state["viewtest"]["Flex189"]);
const Flex189IoProps = useIoStore((state)=>state["viewtest"]["Flex189"]);
const Flex189Cb = useFlex189Cb()
const testnameProps = useStore((state)=>state["viewtest"]["testname"]);
const testnameIoProps = useIoStore((state)=>state["viewtest"]["testname"]);
const testnameCb = usetestnameCb()
const Flex190Props = useStore((state)=>state["viewtest"]["Flex190"]);
const Flex190IoProps = useIoStore((state)=>state["viewtest"]["Flex190"]);
const Flex190Cb = useFlex190Cb()
const Flex191Props = useStore((state)=>state["viewtest"]["Flex191"]);
const Flex191IoProps = useIoStore((state)=>state["viewtest"]["Flex191"]);
const Flex191Cb = useFlex191Cb()
const Flex192Props = useStore((state)=>state["viewtest"]["Flex192"]);
const Flex192IoProps = useIoStore((state)=>state["viewtest"]["Flex192"]);
const Flex192Cb = useFlex192Cb()
const Image105Props = useStore((state)=>state["viewtest"]["Image105"]);
const Image105IoProps = useIoStore((state)=>state["viewtest"]["Image105"]);
const Image105Cb = useImage105Cb()
const Flex193Props = useStore((state)=>state["viewtest"]["Flex193"]);
const Flex193IoProps = useIoStore((state)=>state["viewtest"]["Flex193"]);
const Flex193Cb = useFlex193Cb()
const Flex194Props = useStore((state)=>state["viewtest"]["Flex194"]);
const Flex194IoProps = useIoStore((state)=>state["viewtest"]["Flex194"]);
const Flex194Cb = useFlex194Cb()
const Button9Props = useStore((state)=>state["viewtest"]["Button9"]);
const Button9IoProps = useIoStore((state)=>state["viewtest"]["Button9"]);
const Button9Cb = useButton9Cb()
const TextBox81Props = useStore((state)=>state["viewtest"]["TextBox81"]);
const TextBox81IoProps = useIoStore((state)=>state["viewtest"]["TextBox81"]);
const TextBox81Cb = useTextBox81Cb()
const Flex197Props = useStore((state)=>state["viewtest"]["Flex197"]);
const Flex197IoProps = useIoStore((state)=>state["viewtest"]["Flex197"]);
const Flex197Cb = useFlex197Cb()
const TextBox82Props = useStore((state)=>state["viewtest"]["TextBox82"]);
const TextBox82IoProps = useIoStore((state)=>state["viewtest"]["TextBox82"]);
const TextBox82Cb = useTextBox82Cb()
const TextBox83Props = useStore((state)=>state["viewtest"]["TextBox83"]);
const TextBox83IoProps = useIoStore((state)=>state["viewtest"]["TextBox83"]);
const TextBox83Cb = useTextBox83Cb()
const Flex200Props = useStore((state)=>state["viewtest"]["Flex200"]);
const Flex200IoProps = useIoStore((state)=>state["viewtest"]["Flex200"]);
const Flex200Cb = useFlex200Cb()
const Flex201Props = useStore((state)=>state["viewtest"]["Flex201"]);
const Flex201IoProps = useIoStore((state)=>state["viewtest"]["Flex201"]);
const Flex201Cb = useFlex201Cb()
const TextBox85Props = useStore((state)=>state["viewtest"]["TextBox85"]);
const TextBox85IoProps = useIoStore((state)=>state["viewtest"]["TextBox85"]);
const TextBox85Cb = useTextBox85Cb()
const Flex202Props = useStore((state)=>state["viewtest"]["Flex202"]);
const Flex202IoProps = useIoStore((state)=>state["viewtest"]["Flex202"]);
const Flex202Cb = useFlex202Cb()
const Flex203Props = useStore((state)=>state["viewtest"]["Flex203"]);
const Flex203IoProps = useIoStore((state)=>state["viewtest"]["Flex203"]);
const Flex203Cb = useFlex203Cb()
const TextBox87Props = useStore((state)=>state["viewtest"]["TextBox87"]);
const TextBox87IoProps = useIoStore((state)=>state["viewtest"]["TextBox87"]);
const TextBox87Cb = useTextBox87Cb()
const Flex204Props = useStore((state)=>state["viewtest"]["Flex204"]);
const Flex204IoProps = useIoStore((state)=>state["viewtest"]["Flex204"]);
const Flex204Cb = useFlex204Cb()
const Flex205Props = useStore((state)=>state["viewtest"]["Flex205"]);
const Flex205IoProps = useIoStore((state)=>state["viewtest"]["Flex205"]);
const Flex205Cb = useFlex205Cb()
const TextBox89Props = useStore((state)=>state["viewtest"]["TextBox89"]);
const TextBox89IoProps = useIoStore((state)=>state["viewtest"]["TextBox89"]);
const TextBox89Cb = useTextBox89Cb()
const Button13Props = useStore((state)=>state["viewtest"]["Button13"]);
const Button13IoProps = useIoStore((state)=>state["viewtest"]["Button13"]);
const Button13Cb = useButton13Cb()
const TextBox91Props = useStore((state)=>state["viewtest"]["TextBox91"]);
const TextBox91IoProps = useIoStore((state)=>state["viewtest"]["TextBox91"]);
const TextBox91Cb = useTextBox91Cb()
const Flex208Props = useStore((state)=>state["viewtest"]["Flex208"]);
const Flex208IoProps = useIoStore((state)=>state["viewtest"]["Flex208"]);
const Flex208Cb = useFlex208Cb()
const Flex209Props = useStore((state)=>state["viewtest"]["Flex209"]);
const Flex209IoProps = useIoStore((state)=>state["viewtest"]["Flex209"]);
const Flex209Cb = useFlex209Cb()
const TextBox93Props = useStore((state)=>state["viewtest"]["TextBox93"]);
const TextBox93IoProps = useIoStore((state)=>state["viewtest"]["TextBox93"]);
const TextBox93Cb = useTextBox93Cb()
const TextBox94Props = useStore((state)=>state["viewtest"]["TextBox94"]);
const TextBox94IoProps = useIoStore((state)=>state["viewtest"]["TextBox94"]);
const TextBox94Cb = useTextBox94Cb()
const TextBox95Props = useStore((state)=>state["viewtest"]["TextBox95"]);
const TextBox95IoProps = useIoStore((state)=>state["viewtest"]["TextBox95"]);
const TextBox95Cb = useTextBox95Cb()
const TextBox96Props = useStore((state)=>state["viewtest"]["TextBox96"]);
const TextBox96IoProps = useIoStore((state)=>state["viewtest"]["TextBox96"]);
const TextBox96Cb = useTextBox96Cb()
const Flex211Props = useStore((state)=>state["viewtest"]["Flex211"]);
const Flex211IoProps = useIoStore((state)=>state["viewtest"]["Flex211"]);
const Flex211Cb = useFlex211Cb()
const correctProps = useStore((state)=>state["viewtest"]["correct"]);
const correctIoProps = useIoStore((state)=>state["viewtest"]["correct"]);
const correctCb = usecorrectCb()
const exclaimProps = useStore((state)=>state["viewtest"]["exclaim"]);
const exclaimIoProps = useIoStore((state)=>state["viewtest"]["exclaim"]);
const exclaimCb = useexclaimCb()
const incorrectProps = useStore((state)=>state["viewtest"]["incorrect"]);
const incorrectIoProps = useIoStore((state)=>state["viewtest"]["incorrect"]);
const incorrectCb = useincorrectCb()
const comment_btnProps = useStore((state)=>state["viewtest"]["comment_btn"]);
const comment_btnIoProps = useIoStore((state)=>state["viewtest"]["comment_btn"]);
const comment_btnCb = usecomment_btnCb()
const Flex212Props = useStore((state)=>state["viewtest"]["Flex212"]);
const Flex212IoProps = useIoStore((state)=>state["viewtest"]["Flex212"]);
const Flex212Cb = useFlex212Cb()
const Flex213Props = useStore((state)=>state["viewtest"]["Flex213"]);
const Flex213IoProps = useIoStore((state)=>state["viewtest"]["Flex213"]);
const Flex213Cb = useFlex213Cb()
const TextBox97Props = useStore((state)=>state["viewtest"]["TextBox97"]);
const TextBox97IoProps = useIoStore((state)=>state["viewtest"]["TextBox97"]);
const TextBox97Cb = useTextBox97Cb()
const comment_wrapper_1Props = useStore((state)=>state["viewtest"]["comment_wrapper_1"]);
const comment_wrapper_1IoProps = useIoStore((state)=>state["viewtest"]["comment_wrapper_1"]);
const comment_wrapper_1Cb = usecomment_wrapper_1Cb()
const Flex215Props = useStore((state)=>state["viewtest"]["Flex215"]);
const Flex215IoProps = useIoStore((state)=>state["viewtest"]["Flex215"]);
const Flex215Cb = useFlex215Cb()
const Flex216Props = useStore((state)=>state["viewtest"]["Flex216"]);
const Flex216IoProps = useIoStore((state)=>state["viewtest"]["Flex216"]);
const Flex216Cb = useFlex216Cb()
const Image109Props = useStore((state)=>state["viewtest"]["Image109"]);
const Image109IoProps = useIoStore((state)=>state["viewtest"]["Image109"]);
const Image109Cb = useImage109Cb()
const username_1Props = useStore((state)=>state["viewtest"]["username_1"]);
const username_1IoProps = useIoStore((state)=>state["viewtest"]["username_1"]);
const username_1Cb = useusername_1Cb()
const time_1Props = useStore((state)=>state["viewtest"]["time_1"]);
const time_1IoProps = useIoStore((state)=>state["viewtest"]["time_1"]);
const time_1Cb = usetime_1Cb()
const comment_1Props = useStore((state)=>state["viewtest"]["comment_1"]);
const comment_1IoProps = useIoStore((state)=>state["viewtest"]["comment_1"]);
const comment_1Cb = usecomment_1Cb()
const Flex218Props = useStore((state)=>state["viewtest"]["Flex218"]);
const Flex218IoProps = useIoStore((state)=>state["viewtest"]["Flex218"]);
const Flex218Cb = useFlex218Cb()
const comment_2Props = useStore((state)=>state["viewtest"]["comment_2"]);
const comment_2IoProps = useIoStore((state)=>state["viewtest"]["comment_2"]);
const comment_2Cb = usecomment_2Cb()
const time_2Props = useStore((state)=>state["viewtest"]["time_2"]);
const time_2IoProps = useIoStore((state)=>state["viewtest"]["time_2"]);
const time_2Cb = usetime_2Cb()
const username_2Props = useStore((state)=>state["viewtest"]["username_2"]);
const username_2IoProps = useIoStore((state)=>state["viewtest"]["username_2"]);
const username_2Cb = useusername_2Cb()
const Image110Props = useStore((state)=>state["viewtest"]["Image110"]);
const Image110IoProps = useIoStore((state)=>state["viewtest"]["Image110"]);
const Image110Cb = useImage110Cb()
const Flex219Props = useStore((state)=>state["viewtest"]["Flex219"]);
const Flex219IoProps = useIoStore((state)=>state["viewtest"]["Flex219"]);
const Flex219Cb = useFlex219Cb()
const Flex220Props = useStore((state)=>state["viewtest"]["Flex220"]);
const Flex220IoProps = useIoStore((state)=>state["viewtest"]["Flex220"]);
const Flex220Cb = useFlex220Cb()
const comment_wrapper_2Props = useStore((state)=>state["viewtest"]["comment_wrapper_2"]);
const comment_wrapper_2IoProps = useIoStore((state)=>state["viewtest"]["comment_wrapper_2"]);
const comment_wrapper_2Cb = usecomment_wrapper_2Cb()
const Image111Props = useStore((state)=>state["viewtest"]["Image111"]);
const Image111IoProps = useIoStore((state)=>state["viewtest"]["Image111"]);
const Image111Cb = useImage111Cb()
const username_3Props = useStore((state)=>state["viewtest"]["username_3"]);
const username_3IoProps = useIoStore((state)=>state["viewtest"]["username_3"]);
const username_3Cb = useusername_3Cb()
const time_3Props = useStore((state)=>state["viewtest"]["time_3"]);
const time_3IoProps = useIoStore((state)=>state["viewtest"]["time_3"]);
const time_3Cb = usetime_3Cb()
const comment_3Props = useStore((state)=>state["viewtest"]["comment_3"]);
const comment_3IoProps = useIoStore((state)=>state["viewtest"]["comment_3"]);
const comment_3Cb = usecomment_3Cb()
const Flex222Props = useStore((state)=>state["viewtest"]["Flex222"]);
const Flex222IoProps = useIoStore((state)=>state["viewtest"]["Flex222"]);
const Flex222Cb = useFlex222Cb()
const Flex223Props = useStore((state)=>state["viewtest"]["Flex223"]);
const Flex223IoProps = useIoStore((state)=>state["viewtest"]["Flex223"]);
const Flex223Cb = useFlex223Cb()
const comment_wrapper_3Props = useStore((state)=>state["viewtest"]["comment_wrapper_3"]);
const comment_wrapper_3IoProps = useIoStore((state)=>state["viewtest"]["comment_wrapper_3"]);
const comment_wrapper_3Cb = usecomment_wrapper_3Cb()
const comment_input_wrapperProps = useStore((state)=>state["viewtest"]["comment_input_wrapper"]);
const comment_input_wrapperIoProps = useIoStore((state)=>state["viewtest"]["comment_input_wrapper"]);
const comment_input_wrapperCb = usecomment_input_wrapperCb()
const comment_inputProps = useStore((state)=>state["viewtest"]["comment_input"]);
const comment_inputIoProps = useIoStore((state)=>state["viewtest"]["comment_input"]);
const comment_inputCb = usecomment_inputCb()
const Button20Props = useStore((state)=>state["viewtest"]["Button20"]);
const Button20IoProps = useIoStore((state)=>state["viewtest"]["Button20"]);
const Button20Cb = useButton20Cb()
const Button49Props = useStore((state)=>state["viewtest"]["Button49"]);
const Button49IoProps = useIoStore((state)=>state["viewtest"]["Button49"]);
const Button49Cb = useButton49Cb()
const Button50Props = useStore((state)=>state["viewtest"]["Button50"]);
const Button50IoProps = useIoStore((state)=>state["viewtest"]["Button50"]);
const Button50Cb = useButton50Cb()
const Button51Props = useStore((state)=>state["viewtest"]["Button51"]);
const Button51IoProps = useIoStore((state)=>state["viewtest"]["Button51"]);
const Button51Cb = useButton51Cb()
const Button52Props = useStore((state)=>state["viewtest"]["Button52"]);
const Button52IoProps = useIoStore((state)=>state["viewtest"]["Button52"]);
const Button52Cb = useButton52Cb()
const Button58Props = useStore((state)=>state["viewtest"]["Button58"]);
const Button58IoProps = useIoStore((state)=>state["viewtest"]["Button58"]);
const Button58Cb = useButton58Cb()
const TextBox198Props = useStore((state)=>state["viewtest"]["TextBox198"]);
const TextBox198IoProps = useIoStore((state)=>state["viewtest"]["TextBox198"]);
const TextBox198Cb = useTextBox198Cb()
const TextBox199Props = useStore((state)=>state["viewtest"]["TextBox199"]);
const TextBox199IoProps = useIoStore((state)=>state["viewtest"]["TextBox199"]);
const TextBox199Cb = useTextBox199Cb()
const Button59Props = useStore((state)=>state["viewtest"]["Button59"]);
const Button59IoProps = useIoStore((state)=>state["viewtest"]["Button59"]);
const Button59Cb = useButton59Cb()
const TextBox200Props = useStore((state)=>state["viewtest"]["TextBox200"]);
const TextBox200IoProps = useIoStore((state)=>state["viewtest"]["TextBox200"]);
const TextBox200Cb = useTextBox200Cb()
const Button60Props = useStore((state)=>state["viewtest"]["Button60"]);
const Button60IoProps = useIoStore((state)=>state["viewtest"]["Button60"]);
const Button60Cb = useButton60Cb()
const TextBox201Props = useStore((state)=>state["viewtest"]["TextBox201"]);
const TextBox201IoProps = useIoStore((state)=>state["viewtest"]["TextBox201"]);
const TextBox201Cb = useTextBox201Cb()
const Button61Props = useStore((state)=>state["viewtest"]["Button61"]);
const Button61IoProps = useIoStore((state)=>state["viewtest"]["Button61"]);
const Button61Cb = useButton61Cb()
const TextBox202Props = useStore((state)=>state["viewtest"]["TextBox202"]);
const TextBox202IoProps = useIoStore((state)=>state["viewtest"]["TextBox202"]);
const TextBox202Cb = useTextBox202Cb()
const Button62Props = useStore((state)=>state["viewtest"]["Button62"]);
const Button62IoProps = useIoStore((state)=>state["viewtest"]["Button62"]);
const Button62Cb = useButton62Cb()
const Image148Props = useStore((state)=>state["viewtest"]["Image148"]);
const Image148IoProps = useIoStore((state)=>state["viewtest"]["Image148"]);
const Image148Cb = useImage148Cb()
const Flex372Props = useStore((state)=>state["viewtest"]["Flex372"]);
const Flex372IoProps = useIoStore((state)=>state["viewtest"]["Flex372"]);
const Flex372Cb = useFlex372Cb()
const TextBox203Props = useStore((state)=>state["viewtest"]["TextBox203"]);
const TextBox203IoProps = useIoStore((state)=>state["viewtest"]["TextBox203"]);
const TextBox203Cb = useTextBox203Cb()
const Flex373Props = useStore((state)=>state["viewtest"]["Flex373"]);
const Flex373IoProps = useIoStore((state)=>state["viewtest"]["Flex373"]);
const Flex373Cb = useFlex373Cb()
const TextBox204Props = useStore((state)=>state["viewtest"]["TextBox204"]);
const TextBox204IoProps = useIoStore((state)=>state["viewtest"]["TextBox204"]);
const TextBox204Cb = useTextBox204Cb()
const Flex374Props = useStore((state)=>state["viewtest"]["Flex374"]);
const Flex374IoProps = useIoStore((state)=>state["viewtest"]["Flex374"]);
const Flex374Cb = useFlex374Cb()
const TextBox205Props = useStore((state)=>state["viewtest"]["TextBox205"]);
const TextBox205IoProps = useIoStore((state)=>state["viewtest"]["TextBox205"]);
const TextBox205Cb = useTextBox205Cb()
const Flex375Props = useStore((state)=>state["viewtest"]["Flex375"]);
const Flex375IoProps = useIoStore((state)=>state["viewtest"]["Flex375"]);
const Flex375Cb = useFlex375Cb()
const TextBox206Props = useStore((state)=>state["viewtest"]["TextBox206"]);
const TextBox206IoProps = useIoStore((state)=>state["viewtest"]["TextBox206"]);
const TextBox206Cb = useTextBox206Cb()
const Flex376Props = useStore((state)=>state["viewtest"]["Flex376"]);
const Flex376IoProps = useIoStore((state)=>state["viewtest"]["Flex376"]);
const Flex376Cb = useFlex376Cb()
const TextBox207Props = useStore((state)=>state["viewtest"]["TextBox207"]);
const TextBox207IoProps = useIoStore((state)=>state["viewtest"]["TextBox207"]);
const TextBox207Cb = useTextBox207Cb()
const Flex377Props = useStore((state)=>state["viewtest"]["Flex377"]);
const Flex377IoProps = useIoStore((state)=>state["viewtest"]["Flex377"]);
const Flex377Cb = useFlex377Cb()
const Flex378Props = useStore((state)=>state["viewtest"]["Flex378"]);
const Flex378IoProps = useIoStore((state)=>state["viewtest"]["Flex378"]);
const Flex378Cb = useFlex378Cb()
const Flex379Props = useStore((state)=>state["viewtest"]["Flex379"]);
const Flex379IoProps = useIoStore((state)=>state["viewtest"]["Flex379"]);
const Flex379Cb = useFlex379Cb()
const Flex380Props = useStore((state)=>state["viewtest"]["Flex380"]);
const Flex380IoProps = useIoStore((state)=>state["viewtest"]["Flex380"]);
const Flex380Cb = useFlex380Cb()
const Flex381Props = useStore((state)=>state["viewtest"]["Flex381"]);
const Flex381IoProps = useIoStore((state)=>state["viewtest"]["Flex381"]);
const Flex381Cb = useFlex381Cb()
const Flex382Props = useStore((state)=>state["viewtest"]["Flex382"]);
const Flex382IoProps = useIoStore((state)=>state["viewtest"]["Flex382"]);
const Flex382Cb = useFlex382Cb()
const Flex386Props = useStore((state)=>state["viewtest"]["Flex386"]);
const Flex386IoProps = useIoStore((state)=>state["viewtest"]["Flex386"]);
const Flex386Cb = useFlex386Cb()
const Button63Props = useStore((state)=>state["viewtest"]["Button63"]);
const Button63IoProps = useIoStore((state)=>state["viewtest"]["Button63"]);
const Button63Cb = useButton63Cb()
const TextBox208Props = useStore((state)=>state["viewtest"]["TextBox208"]);
const TextBox208IoProps = useIoStore((state)=>state["viewtest"]["TextBox208"]);
const TextBox208Cb = useTextBox208Cb()
const TextBox209Props = useStore((state)=>state["viewtest"]["TextBox209"]);
const TextBox209IoProps = useIoStore((state)=>state["viewtest"]["TextBox209"]);
const TextBox209Cb = useTextBox209Cb()
const Button64Props = useStore((state)=>state["viewtest"]["Button64"]);
const Button64IoProps = useIoStore((state)=>state["viewtest"]["Button64"]);
const Button64Cb = useButton64Cb()
const TextBox210Props = useStore((state)=>state["viewtest"]["TextBox210"]);
const TextBox210IoProps = useIoStore((state)=>state["viewtest"]["TextBox210"]);
const TextBox210Cb = useTextBox210Cb()
const Button65Props = useStore((state)=>state["viewtest"]["Button65"]);
const Button65IoProps = useIoStore((state)=>state["viewtest"]["Button65"]);
const Button65Cb = useButton65Cb()
const TextBox211Props = useStore((state)=>state["viewtest"]["TextBox211"]);
const TextBox211IoProps = useIoStore((state)=>state["viewtest"]["TextBox211"]);
const TextBox211Cb = useTextBox211Cb()
const Button66Props = useStore((state)=>state["viewtest"]["Button66"]);
const Button66IoProps = useIoStore((state)=>state["viewtest"]["Button66"]);
const Button66Cb = useButton66Cb()
const TextBox212Props = useStore((state)=>state["viewtest"]["TextBox212"]);
const TextBox212IoProps = useIoStore((state)=>state["viewtest"]["TextBox212"]);
const TextBox212Cb = useTextBox212Cb()
const Button67Props = useStore((state)=>state["viewtest"]["Button67"]);
const Button67IoProps = useIoStore((state)=>state["viewtest"]["Button67"]);
const Button67Cb = useButton67Cb()
const output_imgProps = useStore((state)=>state["viewtest"]["output_img"]);
const output_imgIoProps = useIoStore((state)=>state["viewtest"]["output_img"]);
const output_imgCb = useoutput_imgCb()
const Flex387Props = useStore((state)=>state["viewtest"]["Flex387"]);
const Flex387IoProps = useIoStore((state)=>state["viewtest"]["Flex387"]);
const Flex387Cb = useFlex387Cb()
const driver_nameProps = useStore((state)=>state["viewtest"]["driver_name"]);
const driver_nameIoProps = useIoStore((state)=>state["viewtest"]["driver_name"]);
const driver_nameCb = usedriver_nameCb()
const Flex388Props = useStore((state)=>state["viewtest"]["Flex388"]);
const Flex388IoProps = useIoStore((state)=>state["viewtest"]["Flex388"]);
const Flex388Cb = useFlex388Cb()
const licenseProps = useStore((state)=>state["viewtest"]["license"]);
const licenseIoProps = useIoStore((state)=>state["viewtest"]["license"]);
const licenseCb = uselicenseCb()
const Flex389Props = useStore((state)=>state["viewtest"]["Flex389"]);
const Flex389IoProps = useIoStore((state)=>state["viewtest"]["Flex389"]);
const Flex389Cb = useFlex389Cb()
const dobProps = useStore((state)=>state["viewtest"]["dob"]);
const dobIoProps = useIoStore((state)=>state["viewtest"]["dob"]);
const dobCb = usedobCb()
const Flex390Props = useStore((state)=>state["viewtest"]["Flex390"]);
const Flex390IoProps = useIoStore((state)=>state["viewtest"]["Flex390"]);
const Flex390Cb = useFlex390Cb()
const expiryProps = useStore((state)=>state["viewtest"]["expiry"]);
const expiryIoProps = useIoStore((state)=>state["viewtest"]["expiry"]);
const expiryCb = useexpiryCb()
const Flex391Props = useStore((state)=>state["viewtest"]["Flex391"]);
const Flex391IoProps = useIoStore((state)=>state["viewtest"]["Flex391"]);
const Flex391Cb = useFlex391Cb()
const addressProps = useStore((state)=>state["viewtest"]["address"]);
const addressIoProps = useIoStore((state)=>state["viewtest"]["address"]);
const addressCb = useaddressCb()
const output_img_wrapperProps = useStore((state)=>state["viewtest"]["output_img_wrapper"]);
const output_img_wrapperIoProps = useIoStore((state)=>state["viewtest"]["output_img_wrapper"]);
const output_img_wrapperCb = useoutput_img_wrapperCb()
const Flex393Props = useStore((state)=>state["viewtest"]["Flex393"]);
const Flex393IoProps = useIoStore((state)=>state["viewtest"]["Flex393"]);
const Flex393Cb = useFlex393Cb()
const Flex394Props = useStore((state)=>state["viewtest"]["Flex394"]);
const Flex394IoProps = useIoStore((state)=>state["viewtest"]["Flex394"]);
const Flex394Cb = useFlex394Cb()
const Flex395Props = useStore((state)=>state["viewtest"]["Flex395"]);
const Flex395IoProps = useIoStore((state)=>state["viewtest"]["Flex395"]);
const Flex395Cb = useFlex395Cb()
const Flex396Props = useStore((state)=>state["viewtest"]["Flex396"]);
const Flex396IoProps = useIoStore((state)=>state["viewtest"]["Flex396"]);
const Flex396Cb = useFlex396Cb()
const Flex397Props = useStore((state)=>state["viewtest"]["Flex397"]);
const Flex397IoProps = useIoStore((state)=>state["viewtest"]["Flex397"]);
const Flex397Cb = useFlex397Cb()
const Flex398Props = useStore((state)=>state["viewtest"]["Flex398"]);
const Flex398IoProps = useIoStore((state)=>state["viewtest"]["Flex398"]);
const Flex398Cb = useFlex398Cb()
const Flex399Props = useStore((state)=>state["viewtest"]["Flex399"]);
const Flex399IoProps = useIoStore((state)=>state["viewtest"]["Flex399"]);
const Flex399Cb = useFlex399Cb()
const Flex400Props = useStore((state)=>state["viewtest"]["Flex400"]);
const Flex400IoProps = useIoStore((state)=>state["viewtest"]["Flex400"]);
const Flex400Cb = useFlex400Cb()
const Flex401Props = useStore((state)=>state["viewtest"]["Flex401"]);
const Flex401IoProps = useIoStore((state)=>state["viewtest"]["Flex401"]);
const Flex401Cb = useFlex401Cb()
const submitProps = useStore((state)=>state["viewtest"]["submit"]);
const submitIoProps = useIoStore((state)=>state["viewtest"]["submit"]);
const submitCb = usesubmitCb()
const comment_btn_wrapperProps = useStore((state)=>state["viewtest"]["comment_btn_wrapper"]);
const comment_btn_wrapperIoProps = useIoStore((state)=>state["viewtest"]["comment_btn_wrapper"]);
const comment_btn_wrapperCb = usecomment_btn_wrapperCb()
const Image151Props = useStore((state)=>state["viewtest"]["Image151"]);
const Image151IoProps = useIoStore((state)=>state["viewtest"]["Image151"]);
const Image151Cb = useImage151Cb()

  return (<>
  <Flex1 {...Flex185Props} {...Flex185Cb} {...Flex185IoProps}>
<Flex1 {...Flex184Props} {...Flex184Cb} {...Flex184IoProps}>
<Flex1 {...Flex181Props} {...Flex181Cb} {...Flex181IoProps}>
<Image1 {...Image102Props} {...Image102Cb} {...Image102IoProps}/>
</Flex1>
<Flex1 {...Flex182Props} {...Flex182Cb} {...Flex182IoProps}>
<TextBox1 {...TextBox74Props} {...TextBox74Cb} {...TextBox74IoProps}/>
</Flex1>
<Flex1 {...Flex183Props} {...Flex183Cb} {...Flex183IoProps}>
<Button1 {...Button20Props} {...Button20Cb} {...Button20IoProps}/>
<Image1 {...Image151Props} {...Image151Cb} {...Image151IoProps}/>
</Flex1>
</Flex1>
</Flex1>
<Flex1 {...Flex186Props} {...Flex186Cb} {...Flex186IoProps}>
<TextBox1 {...TextBox76Props} {...TextBox76Cb} {...TextBox76IoProps}/>
<Flex1 {...Flex192Props} {...Flex192Cb} {...Flex192IoProps}>
<Flex1 {...Flex191Props} {...Flex191Cb} {...Flex191IoProps}>
<TextBox1 {...testnameProps} {...testnameCb} {...testnameIoProps}/>
</Flex1>
<Flex1 {...Flex190Props} {...Flex190Cb} {...Flex190IoProps}>
<Flex1 {...Flex189Props} {...Flex189Cb} {...Flex189IoProps}>
<Image1 {...Image104Props} {...Image104Cb} {...Image104IoProps}/>
<TextBox1 {...TextBox78Props} {...TextBox78Cb} {...TextBox78IoProps}/>
</Flex1>
<Flex1 {...Flex187Props} {...Flex187Cb} {...Flex187IoProps}>
<Button1 {...Button8Props} {...Button8Cb} {...Button8IoProps}/>
</Flex1>
<Flex1 {...Flex188Props} {...Flex188Cb} {...Flex188IoProps}>
<TextBox1 {...TextBox77Props} {...TextBox77Cb} {...TextBox77IoProps}/>
<Image1 {...Image103Props} {...Image103Cb} {...Image103IoProps}/>
</Flex1>
</Flex1>
</Flex1>
<Flex1 {...Flex386Props} {...Flex386Cb} {...Flex386IoProps}>
<Flex1 {...Flex400Props} {...Flex400Cb} {...Flex400IoProps}>
<Flex1 {...Flex398Props} {...Flex398Cb} {...Flex398IoProps}>
<Flex1 {...output_img_wrapperProps} {...output_img_wrapperCb} {...output_img_wrapperIoProps}>
<Image1 {...output_imgProps} {...output_imgCb} {...output_imgIoProps}/>
</Flex1>
</Flex1>
<Flex1 {...Flex399Props} {...Flex399Cb} {...Flex399IoProps}>
<Flex1 {...Flex393Props} {...Flex393Cb} {...Flex393IoProps}>
<Flex1 {...Flex387Props} {...Flex387Cb} {...Flex387IoProps}>
<Button1 {...Button63Props} {...Button63Cb} {...Button63IoProps}/>
<TextBox1 {...TextBox208Props} {...TextBox208Cb} {...TextBox208IoProps}/>
</Flex1>
<TextBox1 {...driver_nameProps} {...driver_nameCb} {...driver_nameIoProps}/>
</Flex1>
<Flex1 {...Flex394Props} {...Flex394Cb} {...Flex394IoProps}>
<Flex1 {...Flex388Props} {...Flex388Cb} {...Flex388IoProps}>
<Button1 {...Button64Props} {...Button64Cb} {...Button64IoProps}/>
<TextBox1 {...TextBox209Props} {...TextBox209Cb} {...TextBox209IoProps}/>
</Flex1>
<TextBox1 {...licenseProps} {...licenseCb} {...licenseIoProps}/>
</Flex1>
<Flex1 {...Flex395Props} {...Flex395Cb} {...Flex395IoProps}>
<Flex1 {...Flex389Props} {...Flex389Cb} {...Flex389IoProps}>
<Button1 {...Button65Props} {...Button65Cb} {...Button65IoProps}/>
<TextBox1 {...TextBox210Props} {...TextBox210Cb} {...TextBox210IoProps}/>
</Flex1>
<TextBox1 {...dobProps} {...dobCb} {...dobIoProps}/>
</Flex1>
<Flex1 {...Flex396Props} {...Flex396Cb} {...Flex396IoProps}>
<Flex1 {...Flex390Props} {...Flex390Cb} {...Flex390IoProps}>
<Button1 {...Button66Props} {...Button66Cb} {...Button66IoProps}/>
<TextBox1 {...TextBox211Props} {...TextBox211Cb} {...TextBox211IoProps}/>
</Flex1>
<TextBox1 {...expiryProps} {...expiryCb} {...expiryIoProps}/>
</Flex1>
<Flex1 {...Flex397Props} {...Flex397Cb} {...Flex397IoProps}>
<Flex1 {...Flex391Props} {...Flex391Cb} {...Flex391IoProps}>
<Button1 {...Button67Props} {...Button67Cb} {...Button67IoProps}/>
<TextBox1 {...TextBox212Props} {...TextBox212Cb} {...TextBox212IoProps}/>
</Flex1>
<TextBox1 {...addressProps} {...addressCb} {...addressIoProps}/>
</Flex1>
</Flex1>
</Flex1>
</Flex1>
<Flex1 {...Flex211Props} {...Flex211Cb} {...Flex211IoProps}>
<Image1 {...correctProps} {...correctCb} {...correctIoProps}/>
<Image1 {...exclaimProps} {...exclaimCb} {...exclaimIoProps}/>
<Image1 {...incorrectProps} {...incorrectCb} {...incorrectIoProps}/>
</Flex1>
<Flex1 {...Flex212Props} {...Flex212Cb} {...Flex212IoProps}>
<Flex1 {...comment_btn_wrapperProps} {...comment_btn_wrapperCb} {...comment_btn_wrapperIoProps}>
<Button1 {...comment_btnProps} {...comment_btnCb} {...comment_btnIoProps}/>
</Flex1>
<Flex1 {...comment_input_wrapperProps} {...comment_input_wrapperCb} {...comment_input_wrapperIoProps}>
<Input {...comment_inputProps} {...comment_inputCb} {...comment_inputIoProps}/>
<Flex1 {...Flex401Props} {...Flex401Cb} {...Flex401IoProps}>
<Button1 {...submitProps} {...submitCb} {...submitIoProps}/>
</Flex1>
</Flex1>
</Flex1>
<Flex1 {...Flex213Props} {...Flex213Cb} {...Flex213IoProps}>
<TextBox1 {...TextBox97Props} {...TextBox97Cb} {...TextBox97IoProps}/>
<Flex1 {...Flex218Props} {...Flex218Cb} {...Flex218IoProps}>
<Flex1 {...comment_wrapper_1Props} {...comment_wrapper_1Cb} {...comment_wrapper_1IoProps}>
<Flex1 {...Flex215Props} {...Flex215Cb} {...Flex215IoProps}>
<Image1 {...Image109Props} {...Image109Cb} {...Image109IoProps}/>
</Flex1>
<Flex1 {...Flex216Props} {...Flex216Cb} {...Flex216IoProps}>
<TextBox1 {...username_1Props} {...username_1Cb} {...username_1IoProps}/>
<TextBox1 {...time_1Props} {...time_1Cb} {...time_1IoProps}/>
<TextBox1 {...comment_1Props} {...comment_1Cb} {...comment_1IoProps}/>
</Flex1>
</Flex1>
<Flex1 {...comment_wrapper_2Props} {...comment_wrapper_2Cb} {...comment_wrapper_2IoProps}>
<Flex1 {...Flex220Props} {...Flex220Cb} {...Flex220IoProps}>
<Image1 {...Image110Props} {...Image110Cb} {...Image110IoProps}/>
</Flex1>
<Flex1 {...Flex219Props} {...Flex219Cb} {...Flex219IoProps}>
<TextBox1 {...username_2Props} {...username_2Cb} {...username_2IoProps}/>
<TextBox1 {...time_2Props} {...time_2Cb} {...time_2IoProps}/>
<TextBox1 {...comment_2Props} {...comment_2Cb} {...comment_2IoProps}/>
</Flex1>
</Flex1>
<Flex1 {...comment_wrapper_3Props} {...comment_wrapper_3Cb} {...comment_wrapper_3IoProps}>
<Flex1 {...Flex222Props} {...Flex222Cb} {...Flex222IoProps}>
<Image1 {...Image111Props} {...Image111Cb} {...Image111IoProps}/>
</Flex1>
<Flex1 {...Flex223Props} {...Flex223Cb} {...Flex223IoProps}>
<TextBox1 {...username_3Props} {...username_3Cb} {...username_3IoProps}/>
<TextBox1 {...time_3Props} {...time_3Cb} {...time_3IoProps}/>
<TextBox1 {...comment_3Props} {...comment_3Cb} {...comment_3IoProps}/>
</Flex1>
</Flex1>
</Flex1>
</Flex1>
</Flex1>
  </>);
}
